# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180609_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='foodJoint',
            new_name='customer',
        ),
    ]
