# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180609_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cost',
        ),
    ]
