# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180609_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='address',
        ),
    ]
