# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cafe_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foodJoint',
        ),
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafe', to='app.Cafe'),
        ),
    ]
