# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180610_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foodItems',
        ),
    ]
