# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180610_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity_type', models.IntegerField(choices=[(1, 'Dozen'), (2, 'Grams'), (3, 'Pieces'), (4, 'MilliLiter')], default=2)),
                ('availableQuantity', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('foodItems', models.ManyToManyField(blank=True, null=True, to='app.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cafeteria')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Processing'), (3, 'Out For Delivery'), (4, 'Delivered')], default=1),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='storeHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StoreHouse'),
        ),
    ]
