# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180610_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='foodItems',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingridients',
            field=models.ManyToManyField(blank=True, null=True, to='app.Ingredients'),
        ),
    ]
