# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180610_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='ingridients',
        ),
    ]
