# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_fooditem_ingridients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='ingridients1',
            new_name='ingridients',
        ),
    ]
