# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180610_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
