# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_fooditem_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='availableQuantity',
        ),
    ]
