# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_fooditem_availablequantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehouse',
            name='cafeteria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Cafeteria'),
        ),
    ]
